In [192]:
import pandas as pd
x1 = pd.read_csv('../data/X/X1_KODEX(1d).csv')
x2 = pd.read_csv('../data/X/X2_X3_X4_KODEX_PBR_PER_DY.csv')
x5 = pd.read_csv('../data/X/X5_kosdaq150(1d).csv')
x7 = pd.read_csv('../data/X/X7_S&P500_return.csv')
x11 = pd.read_csv('../data/X/X11_WTI.csv')
x12 = pd.read_csv('../data/X/X12_10Y2Y.csv')
x12_1 = pd.read_csv('../data/X/X12_10Y3M.csv')
x13 = pd.read_csv('../data/X/X13_VIX.csv')

In [193]:
y = pd.read_csv('../data/y_rate/y_0900_1000.csv')

In [194]:
x1.drop(columns='Unnamed: 0',inplace=True)
x5.drop(columns='Unnamed: 0',inplace=True)
x7.drop(columns='Unnamed: 0',inplace=True)
x11.drop(columns='Unnamed: 0',inplace=True)
x12.drop(columns='Unnamed: 0',inplace=True)
x12_1.drop(columns='Unnamed: 0',inplace=True)
x13.drop(columns='Unnamed: 0',inplace=True)
y.drop(columns='Unnamed: 0',inplace=True)

In [195]:
col_list = [x1,x2,x5,x7,x11,x12,x12_1,x13]

In [196]:
y['date'] = pd.to_datetime(y['date'], format='%Y%m%d')
x2['date'] = pd.to_datetime(x2['date'], format='%Y%m%d')

In [197]:
for i in col_list :
    i['date'] = pd.to_datetime(i['date'], format='%Y-%m-%d')
    y = pd.merge(y, i, on='date', how='inner')

In [198]:
# "K" 제거 및 숫자로 변환
y['WTI_Volume'] = y['WTI_Volume'].str.replace('K', '').astype(float)

In [199]:
# Convert all columns (except 'date') to float
for col in y.columns:
    if col != 'date':
        y[col] = y[col].astype(float)

In [200]:
y

,date,y_rate,KODEX_return,PER,PBR,Dividend_Yield,Kosdaq150_return,S&P500_return,WTI_change,WTI_Volume,T10Y2Y,T10Y3M,VIX
0,2021-01-05,0.006582,113.0,30.68,1.20,1.42,0.0,28.84,2.55,643.19,0.83,0.87,-1.60
1,2021-01-06,-0.001441,433.0,30.45,1.20,1.43,88.0,35.94,0.81,509.37,0.90,0.95,-0.41
2,2021-01-07,0.008012,514.0,31.11,1.22,1.40,93.0,39.08,0.30,369.29,0.94,0.99,-1.30
3,2021-01-08,0.004373,429.0,32.35,1.27,1.35,73.0,9.63,1.31,499.42,0.99,1.05,-0.87
4,2021-01-11,0.015780,-212.0,32.31,1.27,1.35,-59.0,-3.53,-0.33,394.82,1.01,1.07,0.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,2023-10-18,0.003350,-425.0,18.48,0.89,2.00,-250.0,-42.75,0.51,92.80,-0.28,-0.70,0.86
640,2023-10-19,-0.000766,-255.0,18.12,0.88,2.04,-180.0,-43.36,1.13,72.06,-0.16,-0.62,1.67
641,2023-10-20,-0.009324,-35.0,17.82,0.86,2.08,-35.0,-49.69,-1.53,27.31,-0.14,-0.65,0.12
642,2023-10-23,0.000784,150.0,17.68,0.86,2.09,125.0,6.64,-2.51,315.52,-0.19,-0.72,-1.46
643,2023-10-24,-0.005482,90.0,17.88,0.87,2.07,40.0,11.89,-2.41,370.59,-0.19,-0.75,-1.06

In [201]:
y.to_csv('../data/DataFrame_rate/0900_1000_rate.csv')