In [19]:
import pandas as pd

# 데이터 모두 불러옴
x1 = pd.read_csv('../data/X/X1_KODEX(1d).csv', index_col=0)
x2 = pd.read_csv('../data/X/X2_X3_X4_KODEX_PBR_PER_DY.csv', index_col=0)
x5 = pd.read_csv('../data/X/X5_kosdaq150(1d).csv', index_col=0)
x7 = pd.read_csv('../data/X_minmax/SP_500_MINMAX.csv', index_col=0)
x11 = pd.read_csv('../data/X_minmax/WTI_MINMAX.csv', index_col=0)
x11_1 = pd.read_csv('../data/X/X11_WTI.csv', index_col=0)
x12 = pd.read_csv('../data/X/X12_10Y2Y.csv', index_col=0)
x12_1 = pd.read_csv('../data/X/X12_10Y3M.csv', index_col=0)
x13 = pd.read_csv('../data/X_minmax/VIX_MINMAX.csv', index_col=0)
x14 = pd.read_csv('../data/X_minmax/MINMAX_BIT.csv', index_col=0)

In [20]:
y = pd.read_csv('../data/y_minmax/y_minmax_0905.csv')

In [25]:
col_list = [x1,x2,x5,x7,x11,x12,x12_1,x13,x14]

In [23]:
y['date'] = pd.to_datetime(y['date'], format='%Y%m%d')
x2['date'] = pd.to_datetime(x2['date'], format='%Y%m%d')
x7['date'] = pd.to_datetime(x7['날짜'], format='%Y- %m- %d')
x11['date'] = pd.to_datetime(x11['날짜'], format='%Y- %m- %d')
x13['date'] = pd.to_datetime(x13['날짜'], format='%Y-%m-%d')
x14['date'] = pd.to_datetime(x14['Date'], format='%Y-%m-%d')

In [24]:
x7.drop(columns='날짜',inplace=True)
x11.drop(columns='날짜',inplace=True)
x13.drop(columns='날짜',inplace=True)
x14.drop(columns='Date',inplace=True)

In [26]:
for i in col_list :
    i['date'] = pd.to_datetime(i['date'], format='%Y-%m-%d')
    y = pd.merge(y, i, on='date', how='inner')

In [27]:
y

,date,y_minmax,KODEX_return,PER,PBR,Dividend_Yield,Kosdaq150_return,MINMAX_SP_500,WTI_MINMAX,T10Y2Y,T10Y3M,VIX_MINMAX,MINMAX_BTC
0,2021-01-05,151,113.0,30.68,1.20,1.42,0.0,42,2.96,0.83,0.87,3.80,2928000.0
1,2021-01-06,273,433.0,30.45,1.20,1.43,88.0,78,1.46,0.90,0.95,4.63,1680000.0
2,2021-01-07,118,514.0,31.11,1.22,1.40,93.0,47,0.89,0.94,0.99,1.66,3159000.0
3,2021-01-08,156,429.0,32.35,1.27,1.35,73.0,43,1.94,0.99,1.05,1.92,2724000.0
4,2021-01-11,282,-212.0,32.31,1.27,1.35,-59.0,28,1.20,1.01,1.07,1.58,2436000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
660,2023-10-18,70,-425.0,18.48,0.89,2.00,-250.0,61,2.68,-0.28,-0.70,2.27,-192000.0
661,2023-10-19,105,-255.0,18.12,0.88,2.04,-180.0,70,4.08,-0.16,-0.62,2.85,347000.0
662,2023-10-20,100,-35.0,17.82,0.86,2.08,-35.0,53,2.45,-0.14,-0.65,1.41,627000.0
663,2023-10-23,70,150.0,17.68,0.86,2.09,125.0,66,2.94,-0.19,-0.72,3.60,2865000.0
664,2023-10-24,90,90.0,17.88,0.87,2.07,40.0,40,3.36,-0.19,-0.75,1.59,699000.0

In [28]:
# "K" 제거 및 숫자로 변환
y['WTI_Volume'] = y['WTI_Volume'].str.replace('K', '').astype(float)

KeyError: 'WTI_Volume'

In [199]:
# Convert all columns (except 'date') to float
for col in y.columns:
    if col != 'date':
        y[col] = y[col].astype(float)

In [200]:
y

,date,y_rate,KODEX_return,PER,PBR,Dividend_Yield,Kosdaq150_return,S&P500_return,WTI_change,WTI_Volume,T10Y2Y,T10Y3M,VIX
0,2021-01-05,0.006582,113.0,30.68,1.20,1.42,0.0,28.84,2.55,643.19,0.83,0.87,-1.60
1,2021-01-06,-0.001441,433.0,30.45,1.20,1.43,88.0,35.94,0.81,509.37,0.90,0.95,-0.41
2,2021-01-07,0.008012,514.0,31.11,1.22,1.40,93.0,39.08,0.30,369.29,0.94,0.99,-1.30
3,2021-01-08,0.004373,429.0,32.35,1.27,1.35,73.0,9.63,1.31,499.42,0.99,1.05,-0.87
4,2021-01-11,0.015780,-212.0,32.31,1.27,1.35,-59.0,-3.53,-0.33,394.82,1.01,1.07,0.77
...,...,...,...,...,...,...,...,...,...,...,...,...,...
639,2023-10-18,0.003350,-425.0,18.48,0.89,2.00,-250.0,-42.75,0.51,92.80,-0.28,-0.70,0.86
640,2023-10-19,-0.000766,-255.0,18.12,0.88,2.04,-180.0,-43.36,1.13,72.06,-0.16,-0.62,1.67
641,2023-10-20,-0.009324,-35.0,17.82,0.86,2.08,-35.0,-49.69,-1.53,27.31,-0.14,-0.65,0.12
642,2023-10-23,0.000784,150.0,17.68,0.86,2.09,125.0,6.64,-2.51,315.52,-0.19,-0.72,-1.46
643,2023-10-24,-0.005482,90.0,17.88,0.87,2.07,40.0,11.89,-2.41,370.59,-0.19,-0.75,-1.06

In [201]:
y.to_csv('../data/DataFrame_rate/0900_1000_rate.csv')